// Success
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_ALL_PRODUCT_LIST_SUCCESS = "GET_ALL_PRODUCT_LIST_SUCCESS"
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS"
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"


// Error
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR"
export const GET_ALL_PRODUCT_LIST_ERROR = "GET_ALL_PRODUCT_LIST_ERROR"
export const GET_DEPARTMENTS_ERROR = "GET_DEPARTMENTS_ERROR"
export const GET_ALL_PRODUCT_DETAIL_ERROR = "GET_ALL_PRODUCT_DETAIL_ERROR"
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR"
export const ADD_CART_ERROR = "ADD_CART_ERROR"
export const GET_CART_ERROR = "GET_CART_ERROR"

