// Success
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_ALL_PRODUCT_LIST_SUCCESS = "GET_ALL_PRODUCT_LIST_SUCCESS"
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS"
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS"
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS"
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS"
export const GET_PRODUCT_BY_QUERY_STRING_SUCCESS = "GET_PRODUCT_BY_QUERY_STRING_SUCCESS"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_ALL_PRODUCT_LIST_CAT_SUCCESS = "GET_ALL_PRODUCT_LIST_CAT_SUCCESS"
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS"
export const EMPTY_USER_CART_SUCCESS = "EMPTY_USER_CART_SUCCESS"
export const GET_CART_TOTAL_SUCCESS = "GET_CART_TOTAL_SUCCESS"




// Error
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR"
export const GET_ALL_PRODUCT_LIST_ERROR = "GET_ALL_PRODUCT_LIST_ERROR"
export const GET_DEPARTMENTS_ERROR = "GET_DEPARTMENTS_ERROR"
export const GET_ALL_PRODUCT_DETAIL_ERROR = "GET_ALL_PRODUCT_DETAIL_ERROR"
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR"
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR"
export const GET_PRODUCT_BY_QUERY_STRING_ERROR = "GET_PRODUCT_BY_QUERY_STRING_ERROR"
export const ADD_CART_ERROR = "ADD_CART_ERROR"
export const GET_CART_ERROR = "GET_CART_ERROR"
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR"
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR"
export const EMPTY_USER_CART_ERROR = "EMPTY_USER_CART_ERROR"
export const GET_CART_TOTAL_ERROR = "GET_CART_TOTAL_ERROR"






